### ISSUE TITLE
Doesn't work after upgrade to Next.js 12.0

### ISSUE THREAD

**Issue by chemicalkosek** [elado/next-with-less#11]
Hey. After upgrading to Next.js 12.0 I am getting the following error:

```bash
TypeError: Cannot read property 'oneOf' of undefined
    at Object.webpack (/home/maciek/Dokumenty/websites/bookingapp/frontend/node_modules/next-with-less/dist/index.js:60:15)
    at Object.getBaseWebpackConfig [as default] (/home/maciek/Dokumenty/websites/bookingapp/frontend/node_modules/next/dist/build/webpack-config.js:1251:32)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (/home/maciek/Dokumenty/websites/bookingapp/frontend/node_modules/next/dist/trace/trace.js:74:20)
    at async Span.traceAsyncFn (/home/maciek/Dokumenty/websites/bookingapp/frontend/node_modules/next/dist/trace/trace.js:74:20)
    at async HotReloader.start (/home/maciek/Dokumenty/websites/bookingapp/frontend/node_modules/next/dist/server/dev/hot-reloader.js:307:25)
    at async DevServer.prepare (/home/maciek/Dokumenty/websites/bookingapp/frontend/node_modules/next/dist/server/dev/next-dev-server.js:278:9)
    at async /home/maciek/Dokumenty/websites/bookingapp/frontend/node_modules/next/dist/cli/next-dev.js:126:9
```

**Comment by pailodze** [comment]
still an issue with v2.0.2

`TypeError: Cannot read property 'oneOf' of undefined
    at Object.webpack (/Users/*packages/website/node_modules/next-with-less/dist/index.js:66:15)
    at Object.getBaseWebpackConfig [as default] (/Users/*packages/website/node_modules/next/dist/build/webpack-config.js:1388:32)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (/Users/*packages/website/node_modules/next/dist/trace/trace.js:74:20)
    at async Span.traceAsyncFn (/Users/*packages/website/node_modules/next/dist/trace/trace.js:74:20)
    at async HotReloader.start (/Users/*packages/website/node_modules/next/dist/server/dev/hot-reloader.js:329:25)
    at async DevServer.prepare (/Users/*packages/website/node_modules/next/dist/server/dev/next-dev-server.js:296:9)
    at async /Users/*packages/website/node_modules/next/dist/cli/next-dev.js:130:9`

**Comment by pailodze** [comment]
I think this PR #12  is addressing different issue
